# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: CIS_benchmark_testing
# label used for menu selection
label: test CIS content
description: single capture and test for CIS validation creation and test

type: pan_validation

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - CIS

variables:


snippets:

  # 6.9 Ensure that PAN-DB URL Filtering is used
  # this is an operational command requiring API access to the device
  - name: get_license_info
    cmd: cli
    # This cli command will return xml
    cmd_str: request license info
    output_type: xml
    outputs:
          # let's capture a variable called 'connected_server_ip'
      - name: logging_service_URL
        capture_value: ./entry/description[text()="PAN-DB URL Filtering"]/../expired/text()

  - name: pandb_url_filtering
    label: 6.9 Ensure that PAN-DB URL Filtering is used
    test: logging_service_URL == 'no'
    fail_message: PAN-DB license is not used or inactive
    documentation_link: https://www.paloaltonetworks.com

