# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: CIS_benchmark_testing
# label used for menu selection
label: test CIS content
description: single capture and test for CIS validation creation and test

type: pan_validation

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - CIS

variables:


snippets:

  # 6.12 Ensure all HTTP Header Logging options are enabled
  - name: device_config_file
    cmd: parse
    variable: config
    outputs:
      - name: url_profiles_with_header_logging
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/url-filtering/
          entry[log-http-hdr-user-agent='yes' and log-http-hdr-referer='yes'
          and log-http-hdr-xff='yes']/@name
      - name: url_profiles_without_header_logging
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/url-filtering/
          entry/@name
        filter_items: item not in url_profiles_with_header_logging


  - name: url_filtering_http_header_logging
    label: 6.12 Ensure all HTTP Header Logging options are enabled
    test: url_profiles_without_header_logging | length == 0
    fail_message: |-
      Profiles without heading logging options enabled:
      {{ url_profiles_without_header_logging }}
    documentation_link: https://www.paloaltonetworks.com

