# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: CIS_benchmark_testing
# label used for menu selection
label: test CIS content
description: single capture and test for CIS validation creation and test

type: pan_validation

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - CIS

snippets:

  # 4.1 Ensure 'Antivirus Update Schedule' is set to download and install updates hourly
  - name: device_config_file
    cmd: parse
    variable: config
    outputs:
      - name: av_update
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/update-schedule/anti-virus/recurring[1]

  - name: AV_update_schedule
    label: 4.1 Ensure 'Antivirus Update Schedule' is set to download and install updates hourly
    test: av_update | tag_present('hourly')
    fail_message: |
      {{ av_update }}
    pass_message: |
      {{ av_update }}
    documentation_link: |-
      https://iron-skillet.readthedocs.io/en/docs_dev/viz_guide_panos.html
      #ironskillet-dynamic-updates