# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: CIS_benchmark_testing
# label used for menu selection
label: test CIS content
description: single capture and test for CIS validation creation and test

type: pan_validation

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - CIS

variables:


snippets:

  # 5.7 Ensure 'WildFire Update Schedule' is set to download and install updates every minute
  - name: device_config_file
    cmd: parse
    variable: config
    outputs:
      - name: wf_update_schedule_recurring
        capture_object: |-
          /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/update-schedule/
          wildfire[count(recurring) and (count(recurring/real-time) or count(recurring/every-min))]

  - name: WF_update_schedule
    label: 5.7 Ensure 'WildFire Update Schedule' is set to download and install updates every minute
    test: wf_update_schedule_recurring
    fail_message: Wildfire Update Schedule not configured for one-minute or real-time updates
    documentation_link: https://www.paloaltonetworks.com


