# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: CIS_benchmark_testing
# label used for menu selection
label: test CIS content
description: single capture and test for CIS validation creation and test

type: pan_validation

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - CIS

variables:


snippets:

  # 6.5 Ensure passive DNS monitoring is set to enabled on all anti-spyware profiles in use
  # this moved to a telemetry configuration option in 9.x
  # passive DNS and telemetry configuration will change in PAN-OS 10.0
  - name: device_config_file
    cmd: parse
    variable: config
    outputs:
      - name: telemetry_passive_dns_monitoring
        capture_value: |-
          /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/update-schedule/statistics-service/
          passive-dns-monitoring/text()


  - name: enable_passive_DNS_monitoring
    label: 6.5 Ensure passive DNS monitoring is set to enabled on all anti-spyware profiles in use
    test: telemetry_passive_dns_monitoring != 'no'
    fail_message: Passive DNS monitoring is not currently enabled
    documentation_link: https://www.paloaltonetworks.com

