# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: CIS_benchmark_testing
# label used for menu selection
label: test CIS content
description: single capture and test for CIS validation creation and test

type: pan_validation

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - CIS

variables:


snippets:

  # 5.3 Ensure a WildFire Analysis profile is enabled for all security policies
  - name: device_config_file
    cmd: parse
    variable: config
    outputs:
      - name: security_rule_names
        capture_object: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/setting

  - name: WF_forward_decrypt_content
    label: 5.3 Ensure a WildFire Analysis profile is enabled for all security policies
    test: false
    fail_message: test is not implemented
    documentation_link: https://www.paloaltonetworks.com