# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: CIS_benchmark_testing
# label used for menu selection
label: test CIS content
description: single capture and test for CIS validation creation and test

type: pan_validation

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - CIS

variables:

snippets:


  # 6.19 Ensure all zones have Zone Protection Profiles that drop specially crafted packets
  # test checks for all zones having a zone protect profile with recommended settings enabled
  - name: device_config_file
    cmd: parse
    variable: config
    outputs:
      - name: zone_protect_profile_pkt_attack_enabled
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/network/profiles/zone-protection-profile/entry
          [discard-ip-spoof='yes' and discard-strict-source-routing='yes' and
          discard-loose-source-routing='yes' and discard-malformed-option='yes' and
          discard-overlapping-tcp-segment-mismatch='yes']/@name
      - name: zones_with_pkt_attack_enabled_object
        capture_object: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/zone/entry
        filter_items: |-
          item | element_value('network.zone-protection-profile') in zone_protect_profile_pkt_attack_enabled
      - name: zones_with_pkt_attack_enabled_names
        capture_expression: zones_with_pkt_attack_enabled_object | map(attribute="entry.@name") | list
      - name: zones_without_pkt_attack_enabled
        capture_list: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/zone/entry/@name
        filter_items: item not in zones_with_pkt_attack_enabled_names

  - name: zone_protect_crafted_pkts
    label: 6.19 Ensure all zones have Zone Protection Profiles that drop specially crafted packets
    test: zones_without_pkt_attack_enabled | length == 0
    fail_message: |-
      The followings are either configured without a zone protect profile or the associated profile
      is not configured with reconn settings enabled:

      {{ zones_without_pkt_attack_enabled }}
    documentation_link: |-
      https://iron-skillet.readthedocs.io/en/docs_master/cis.html#
      ensure-all-zones-have-zone-protection-profiles-that-drop-specially-crafted-packets
    severity:
      - scored: true
      - level: 1

