# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: CIS_benchmark_testing
# label used for menu selection
label: test CIS content
description: single capture and test for CIS validation creation and test

type: pan_validation

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - CIS

variables:

  - name: app_threat_intervals
    description: interval values used for 4.2 validation
    type_hint: hidden
    default:
      - daily
      - hourly
      - every-30-mins

snippets:

  # 4.2 Ensure 'Applications and Threats Update Schedule'
  - name: device_config_file
    cmd: parse
    variable: config
    outputs:
      - name: threats_update_interval
        capture_value: |-
          /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/
          update-schedule/threats/recurring/*[1]
      - name: threats_update_action
        capture_value: |-
          /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/
          update-schedule/threats/recurring//action/text()

  - name: test_apps_threats_updates
    label: |
      4.2 Ensure 'Applications and Threats Update Schedule' is set to download and install updates
      at daily or shorter intervals
    test: |
      (
        threats_update_interval in app_threat_intervals
        and threats_update_action == 'download-and-install'
      )
    fail_message: |
     Applications and Threats Update Schedule is set to {{ threats_update_interval }}
     with action {{ threats_update_action }}
    pass_message: |
      Applications and Threats Update Schedule is set to {{ threats_update_interval }}
      with action {{ threats_update_action }}
    documentation_link: |-
      https://iron-skillet.readthedocs.io/en/docs_dev/viz_guide_panos.html
      #ironskillet-dynamic-updates