# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: CIS_benchmark_testing
# label used for menu selection
label: test CIS content
description: single capture and test for CIS validation creation and test

type: pan_validation

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - CIS

variables:

  - name: log_types
    description: device log types for log forwarding
    type_hint: hidden
    # globalprotect to be added in 10.0
    default:
      - system
      - config
      - userid
      - hipmatch
      - iptag

snippets:

  # 1.1.1.2 SNMPv3 traps should be configured
  # TODO: future update to include Panorama/CDL option in the checks
  - name: device_config_file
    cmd: parse
    variable: config
    outputs:
      - name: shared_log_settings
        capture_object: /config/shared/log-settings
      - name: logtypes_without_snmp
        capture_variable: |-
          {%- set good_log_types = [] %}
          {%- set bad_log_types = [] %}
          {%- for logtype in shared_log_settings['log-settings'] %}
            {%- if logtype in log_types %}
              {%- for item in shared_log_settings['log-settings'][logtype]['match-list'] %}
                {%- if shared_log_settings['log-settings'][logtype]['match-list'][item][1] %}
                  {%- for entry in shared_log_settings['log-settings'][logtype]['match-list'][item] %}
                    {%- if entry['filter'] == 'All Logs' and entry['send-snmptrap'] %}
                      {%- set _ = good_log_types.append(logtype) %}
                    {%- endif %}
                  {%- endfor %}
                {%- else %}
                  {%- set itemElement = shared_log_settings['log-settings'][logtype]['match-list'][item] %}
                  {%- if itemElement['filter'] == 'All Logs' and itemElement['send-snmptrap'] %}
                    {%- set _ = good_log_types.append(logtype) %}
                  {%- endif %}
                {%- endif %}
              {%- endfor %}
            {%- endif %}
          {%- endfor %}
          {%- for logtype in log_types %}
            {%- if logtype not in good_log_types %}
              {%- set _ = bad_log_types.append(logtype) %}
            {%- endif %}
          {%- endfor %}
          {{ bad_log_types | to_json }}

  - name: system_logging_configured_snmp
    label: 1.1.1.2 SNMPv3 traps should be configured
    test: logtypes_without_snmp | from_json | length == 0
    fail_message: |-
      log types violating benchmark requirement:
      {{ logtypes_without_snmp }}
    documentation_link: https://iron-skillet.readthedocs.io


