# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: CIS_benchmark_testing
# label used for menu selection
label: test CIS content
description: single capture and test for CIS validation creation and test

type: pan_validation

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - CIS

variables:

  - name: wf_file_size_limits
    description: wildfire recommended file size limits
    type_hint: hidden
    default:
      - pe: 16
        apk: 30
        pdf: 3072
        ms-office: 16384
        jar: 5
        flash: 5
        MacOSX: 10
        archive: 50
        linux: 50
        script: 2000

snippets:

  # 5.1 Ensure that WildFire file size upload limits are maximized
  - name: wf_size_testing
    cmd: parse
    variable: config
    outputs:
      - name: wf_file_size_object
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/deviceconfig/setting/wildfire/
          file-size-limit/entry
      - name: wf_filetypes_wo_max_size
        capture_variable: |-
          {%- set bad_filetypes = [] %}
          {%- for item in wf_file_size_object %}
            {%- set filetype = item['entry']['@name'] %}
            {%- if item['entry']['size-limit'] | int < wf_file_size_limits[0][filetype] | int %}
              {%- set _ = bad_filetypes.append(filetype) %}
            {%- endif %}
          {%- endfor %}
          {{ bad_filetypes | to_json }}


  # check all file types and sizes match BPA
  - name:  wf_limit_pe_test
    label: 5.1 Ensure that WildFire file size upload limits are maximized
    test: wf_filetypes_wo_max_size | from_json | length == 0
    fail_message: |-
      filetypes not configured to meet max size requirements:
      {{ wf_filetypes_wo_max_size }}
    documentation_link: www.paloaltonetworks.com


