# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: CIS_benchmark_testing
# label used for menu selection
label: test CIS content
description: single capture and test for CIS validation creation and test

type: pan_validation

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - CIS

variables:


snippets:

  # 5.6 Ensure alerts are enabled for malicious files detected by WildFire
  - name: device_config_file
    cmd: parse
    variable: config
    outputs:
      - name: log_forwarding_profiles_vsys
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/
          log-settings/profiles/entry/@name
      - name: log_forwarding_profiles_wf
        capture_expression: log_forwarding_profiles_vsys
        filter_items: item != 'default'


  - name: WF_alerts_malicious_files
    label: 5.6 Ensure alerts are enabled for malicious files detected by WildFire
    test: false
    fail_message: test is not implemented
    documentation_link: https://www.paloaltonetworks.com
