# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: CIS_benchmark_testing
# label used for menu selection
label: test CIS content
description: single capture and test for CIS validation creation and test

type: pan_validation

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - CIS

variables:


snippets:

  # 6.15 Ensure a secure Data Filtering profile is applied to all security policies allowing traffic to or from the Internet
  - name: device_config_file
    cmd: parse
    variable: config
    outputs:
      # capture for security rules using named profiles instead of a profile group
      - name: security_rules_without_datafiltering_profile
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security
          /rules/entry[action='allow' and count(profile-setting/profiles)>0 and count(data-filtering)=0]/@name
      # capture for security rules using profile groups
      - name: profile_groups_without_datafiltering
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profile-group/
          entry[count(data-filtering)=0]/@name
      - name: security_rules_with_group_without_datafiltering_object
        capture_list: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security
          /rules/entry[action='allow']
        filter_items: item | element_value('profile-setting.group.member') in profile_groups_without_datafiltering
      - name: security_rules_with_group_without_datafiltering_names
        capture_expression: security_rules_with_group_without_datafiltering_object | map(attribute="entry.@name") | list

  - name: datafiltering_profile_in_policies
    label: 6.15 Ensure a secure Data Filtering profile is applied to all security policies allowing traffic to or from the Internet
    test: |-
      (
        security_rules_without_datafiltering_profile | length == 0
        and security_rules_with_group_without_datafiltering_names | length == 0
      )
    fail_message: |-
      security policies without Data Filtering profile:
      Using explicit profile:
      {{ security_rules_without_datafiltering_profile }}
      Using profile group without a Data Filtering profile
      {{ security_rules_with_group_without_datafiltering_names }}
    documentation_link: https://www.paloaltonetworks.com