# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: CIS_benchmark_testing
# label used for menu selection
label: test CIS content
description: single capture and test for CIS validation creation and test

type: pan_validation

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - CIS

snippets:

  # 1.2.2 permitted ip addresses for management profiles
  - name: device_config_file
    cmd: parse
    variable: config
    outputs:
      - name: profile_permitted_ips
        capture_list: /config/devices/entry[@name='localhost.localdomain']/network/profiles/interface-management-profile/entry/permitted-ip/../@name
      - name: profile_ssh_enabled
        capture_list: /config/devices/entry[@name='localhost.localdomain']/network/profiles/interface-management-profile/entry/ssh[text()='yes']/../@name
      - name: profile_https_enabled
        capture_list: /config/devices/entry[@name='localhost.localdomain']/network/profiles/interface-management-profile/entry/https[text()='yes']/../@name
      - name: profile_snmp_enabled
        capture_list: /config/devices/entry[@name='localhost.localdomain']/network/profiles/interface-management-profile/entry/snmp[text()='yes']/../@name
      - name: ssh_https_snmp_enabled_profiles_no_ip_list
        capture_expression: |
          profile_ssh_enabled
          + profile_https_enabled
          + profile_snmp_enabled
        filter_items: item not in profile_permitted_ips


  - name: permitted_ip_address_mgmt_profiles
    label: 1.2.2 Ensure 'Permitted IP Addresses' is set for all management profiles where SSH, HTTPS, or SNMP is enabled
    test: ssh_https_snmp_enabled_profiles_no_ip_list | length == 0
    fail_message: |
      network profiles failing this benchmark are
      {% for item in ssh_https_snmp_enabled_profiles_no_ip_list | unique %}{{ item }} {% endfor %}
    pass_message: all ssh, https, snmp enabled profiles have permitted IP addresses configured
    documentation_link: https://iron-skillet.readthedocs.io