# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: CIS_benchmark_testing
# label used for menu selection
label: test CIS content
description: single capture and test for CIS validation creation and test

type: pan_validation

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - CIS

variables:


snippets:

# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: CIS_benchmark_testing
# label used for menu selection
label: test CIS content
description: single capture and test for CIS validation creation and test

type: pan_validation

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - CIS

variables:

snippets:

  # 6.10 Ensure that URL Filtering uses the action of “block” or “override” on the URL categories
  # TODO: requires user selection for 'categories of interest'
  - name: device_config_file
    cmd: parse
    variable: config
    outputs:
      - name: url_filtering_object
        capture_object: |-
          /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/url-filtering/entry
      - name: url_filtering_block_override
        capture_variable: |-
          {%- set profiles_block_override = dict() %}
          {%- set actions = ['block', 'override'] %}
          {%- for item in url_filtering_object %}
            {%- set entry_dict = dict() %}
            {%- for action in actions %}
              {%- if item['entry'][action] %}
                {%- set configured_categories = [] %}
                {%- if item['entry'][action][1] %}
                  {%- for category in item['entry'][action]['member'] %}
                    {%- set _ = configured_categories.append(category) %}
                  {%- endfor %}
                {%- else %}
                    {%-  set _ = configured_categories.append(item['entry'][action]['member']) %}
                {%- endif %}
                {%- if configured_categories | length %}
                  {%- set _ = entry_dict.update({ action: configured_categories }) %}
                {%- endif %}
              {%- endif %}
            {%- endfor %}
            {%- set _ = profiles_block_override.update({ item['entry']['@name']: entry_dict }) %}
          {%- endfor %}
          {{ profiles_block_override | to_json }}

  - name: url_filtering_block_or_override_test
    label: 6.10 Ensure that URL Filtering uses the action of “block” or “override” on the URL categories
    test: true
    pass_message: |-
      The following profiles are associated categories are found in the configuration.
      Check company practices to validate that these align with 'categories of interest' for block/override
      {{ url_filtering_block_override }}
    documentation_link: |-
      https://iron-skillet.readthedocs.io/en/docs_master/cis.html#
      ensure-that-url-filtering-uses-the-action-of-block-or-override-on-the-url-categories
    severity:
      - scored: true
      - level: 1
      - action_required: true




