# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: CIS_benchmark_testing
# label used for menu selection
label: test CIS content
description: check CDL/EAL setup and firewall configuration to enable IoT

type: pan_validation

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - CIS

snippets:

  - name: device_config_file
    cmd: parse
    variable: config
    outputs:
      - name: system_entry_all_logs
        capture_list: /config/shared/log-settings/system/match-list/entry/filter[text()='All Logs']/../@name
      - name: system_entry_send_snmp_all_logs
        capture_list: /config/shared/log-settings/system/match-list/entry/send-snmptrap/member/../../@name
        filter_items: item in system_entry_all_logs
      - name: config_entry_all_logs
        capture_list: /config/shared/log-settings/config/match-list/entry/filter[text()='All Logs']/../@name
      - name: config_entry_send_snmp_all_logs
        capture_list: /config/shared/log-settings/config/match-list/entry/send-snmptrap/member/../../@name
        filter_items: item in config_entry_all_logs
      - name: userid_entry_all_logs
        capture_list: /config/shared/log-settings/userid/match-list/entry/filter[text()='All Logs']/../@name
      - name: userid_entry_send_snmp_all_logs
        capture_list: /config/shared/log-settings/userid/match-list/entry/send-snmptrap/member/../../@name
        filter_items: item in userid_entry_all_logs
      - name: hipmatch_entry_all_logs
        capture_list: /config/shared/log-settings/hipmatch/match-list/entry/filter[text()='All Logs']/../@name
      - name: hipmatch_entry_send_snmp_all_logs
        capture_list: /config/shared/log-settings/hipmatch/match-list/entry/send-snmptrap/member/../../@name
        filter_items: item in hipmatch_entry_all_logs
      - name: globalprotect_entry_all_logs
        capture_list: /config/shared/log-settings/globalprotect/match-list/entry/filter[text()='All Logs']/../@name
      - name: globalprotect_entry_send_snmp_all_logs
        capture_list: /config/shared/log-settings/globalprotect/match-list/entry/send-snmptrap/member/../../@name
        filter_items: item in globalprotect_entry_all_logs
      - name: iptag_entry_all_logs
        capture_list: /config/shared/log-settings/iptag/match-list/entry/filter[text()='All Logs']/../@name
      - name: iptag_entry_send_snmp_all_logs
        capture_list: /config/shared/log-settings/iptag/match-list/entry/send-snmptrap/member/../../@name
        filter_items: item in iptag_entry_all_logs
      - name: snmpv3_trap_profiles
        capture_list: /config/shared/log-settings/snmptrap/entry/version/v3/../../@name
      - name: logging_snmp_profiles_without_snmp3
        capture_expression: |
          system_entry_send_snmp_all_logs
          + config_entry_send_snmp_all_logs
          + userid_entry_send_snmp_all_logs
          + hipmatch_entry_send_snmp_all_logs
          + globalprotect_entry_send_snmp_all_logs
          + iptag_entry_send_snmp_all_logs
# filter_items: item not in snmpv3_trap_profiles

  - name: snmp_system_logging_configured
    label: 1.1.1.2 SNMPv3 traps should be configured
    test: |
      (
        system_entry_send_snmp_all_logs | length
        and config_entry_send_snmp_all_logs | length
        and userid_entry_send_snmp_all_logs | length
        and hipmatch_entry_send_snmp_all_logs | length
        and globalprotect_entry_send_snmp_all_logs | length
        and iptag_entry_send_snmp_all_logs | length
        and logging_snmp_profiles_without_snmp3 | length == 0
      )
    fail_message: |
      Benchmark fails based on these log settings:
      {%- if system_entry_send_snmp_all_logs | length == 0 %}
      System
      {%- endif %}
      {%- if config_entry_send_snmp_all_logs | length == 0 %}
      Config
      {%- endif %}
      {%- if userid_entry_send_snmp_all_logs | length == 0 %}
      UserID
      {%- endif %}
      {%- if hipmatch_entry_send_snmp_all_logs | length == 0 %}
      HIP Match
      {%- endif %}
      {%- if globalprotect_entry_send_snmp_all_logs | length == 0 %}
      GlobalProtect
      {%- endif %}
      {%- if iptag_entry_send_snmp_all_logs | length == 0 %}
      IP Tag
      {%- endif %}
      {%- if logging_snmp_profiles_without_snmp3 | length %}
      SNMP logging profiles not using version 3: {{ logging_snmp_profiles_without_snmp3 }}
      {%- endif %}
    pass_message: |
      Benchmark passes based on these log settings:
      System: {{ system_entry_send_snmp_all_logs }}
      Config: {{ config_entry_send_snmp_all_logs }}
      UserID: {{ config_entry_send_snmp_all_logs }}
      HIP Match: {{ hipmatch_send_snmp_syslog_all_logs }}
      GlobalProtect: {{ globalprotect_entry_send_snmp_all_logs }}
      IP Tag: {{ iptag_entry_send_snmp_all_logs }}
    documentation_link: https://iron-skillet.readthedocs.io
